### ISSUE TITLE
Can we use this for Asus-K55A ?

### ISSUE THREAD

**Issue by encku** [cobaohieu/ASUS-K55VD-HACKINTOSH#13]

**Comment by cobaohieu** [comment]
Try

**Comment by encku** [comment]
10.14.0 Mojave

Yes it is working on Asus K55A i added SSDT for turbo boost and full acceleration ("i7 3610QM") with https://github.com/Piker-Alpha/ssdtPRGen.sh. 

I don't know my pc has bluetooth or not because that chip optional packet for Asus K55A.

CPU steps. (with SSDT for i7 3610QM [SSDT.aml](https://github.com/southernvevo/ASUS-K55VD-HACKINTOSH/files/2519020/SSDT.aml.zip)) 
Multitouch. (Just two fingers)
Fn keys are working.
Audio is working.
Sleep is working.
Usb 3 and Usb 2 slots are working.
Wifi is working.
Bluetooth i am not sure. (Optional)
Battery percentage and charge icon are working.
Intel hd4000 is working. (Not External GPU on my K55a)

Thank you for sharing @southernvevo .
