### ISSUE TITLE
Mojave 10.14.4 EFI

### ISSUE THREAD

**Issue by unalozturk** [cobaohieu/ASUS-K55VD-HACKINTOSH#18]
I have updated my hackintosh to Mojave 10.14.4. There is a black screen after boot. Could you publish EFI for Mojave 10.14.4 Version?

**Comment by unalozturk** [comment]
While booting with 10.14.13 EFI , I have checked logs with -v mode. There are "AppleKeyStore operation failed" and "timeout "AppleACPICPU", "MCHC"" errors.

**Comment by unalozturk** [comment]
I have found solution. It is because of Clover version. It should be updated to Clover v4895 version but System boots now but drivers seem not okey. It will be better EFI which is tested from you

**Comment by cobaohieu** [comment]
Please check my newest releases.

**Comment by unalozturk** [comment]
Thank you for your effort.
