### ISSUE TITLE
cpu help

### ISSUE THREAD

**Issue by heningcai** [cobaohieu/ASUS-K55VD-HACKINTOSH#19]
I have an ASUS K55vd, but the processor is Intel Core i7-3630QM, the hard drive is Crucial_CT250MX200SSD1, ram 8GB DDR3, can I use this EFI?

**Comment by cobaohieu** [comment]
Please, try it and feedback to me.

**Comment by heningcai** [comment]
Yes, this efi can be used, and Turbo is implemented by your script and manual replacement of SSDT. Thank you for your contribution.

**Comment by lazaropower** [comment]
@heningcai I have the same CPU/RAM as you and I was using this EFI without making any changes. But when I closed the laptop, it never went to sleep, fan stopped but started to work after several seconds. This thing happend to you? If not, let me know what did you do yo replace your SSDT. Thanks :)

**Comment by cobaohieu** [comment]
Go to site and download script and do it with that guide. Mount EFI partition then copy ssdt.aml to Clover folder with path \EFI\CLOVER\ACPI\patched .
https://github.com/Piker-Alpha/ssdtPRGen.sh

**Comment by cobaohieu** [comment]
Please give me your ssdt.aml after your laptop's working. I'll update it with my source. Thanks.

**Comment by heningcai** [comment]
> @heningcai I have the same CPU/RAM as you and I was using this EFI without making any changes. But when I closed the laptop, it never went to sleep, fan stopped but started to work after several seconds. This thing happend to you? If not, let me know what did you do yo replace your SSDT. Thanks :)

My sleep is normal and I have not done anything. I changed ssdt because I wanted CPU frequency conversion and Turbo, and it has been implemented.

**Comment by heningcai** [comment]
> Please give me your ssdt.aml after your laptop's working. I'll update it with my source. Thanks.

[SSDT.aml.zip](https://github.com/cobaohieu/ASUS-K55VD-HACKINTOSH/files/3110540/SSDT.aml.zip)
<img width="404" alt="屏幕快照 2019-04-24 12 06 22" src="https://user-images.githubusercontent.com/20138993/56632234-660b1380-668b-11e9-8522-9315b79f5640.png">

**Comment by cobaohieu** [comment]
> > Please give me your ssdt.aml after your laptop's working. I'll update it with my source. Thanks.
> 
> [SSDT.aml.zip](https://github.com/cobaohieu/ASUS-K55VD-HACKINTOSH/files/3110540/SSDT.aml.zip)
> <img alt="屏幕快照 2019-04-24 12 06 22" width="404" src="https://user-images.githubusercontent.com/20138993/56632234-660b1380-668b-11e9-8522-9315b79f5640.png">

I was disable turbo boost via kext with path \EFI\CLOVER\Kext\Other\DisableTurboBoost.kext (You can remove it to making turbo boost work -> It'll cause increase temperature)
Do not use this app to checking your turbo boost 'cause this app no longer update.

**Comment by heningcai** [comment]
@cobaohieu thanks
