### ISSUE TITLE
10.13: Click here move to folder. link not found

### ISSUE THREAD

**Issue by quynv186** [cobaohieu/ASUS-K55VD-HACKINTOSH#3]
10.13: Click here move to folder. link not found

**Comment by Sadykow** [comment]
https://github.com/southernvevo/ASUS-K55VD-HACKINTOSH/tree/master/10.13.2

It's misses full version number.

**Comment by cobaohieu** [comment]
I fixed.

**Comment by quynv186** [comment]
I setup successfully high sierra 10.13.3 with EFI_10.13.2 folder. Thanks U
