### ISSUE TITLE
Thank you very much for sharing!!! Especially the WiFi and Bluetooth repair of the latest system!!! Thank you.

### ISSUE THREAD

**Issue by libxing** [cobaohieu/ASUS-K55VD-HACKINTOSH#34]
Thank you so much! By the way, will you update Big Sur?

**Comment by cobaohieu** [comment]
Your welcome

**Comment by cobaohieu** [comment]
Thanks for the question.
Please check my release to download the Big Sur with OpenCore
https://github.com/cobaohieu/ASUS-K55VD-HACKINTOSH/releases

**Comment by libxing** [comment]
I'm so shocked. Thank you for sharing!!!
