### ISSUE TITLE
Problem with audio, HDMI port and graphics

### ISSUE THREAD

**Issue by javierangulo94** [cobaohieu/ASUS-K55VD-HACKINTOSH#36]
Hello, thank you very much for your tutorial, it was very helpful to be able to hackintosh my k55vd, I'll tell you that I'm in Mojave first, it's my first experience, I have some problems that I don't know if you can help me, first, the audio doesn't work I've tried with some kext but nothing, I have also not been able to enable the HDMI port and when I use some programs the screen does not show everything and it fails.
[EFI.zip](https://github.com/cobaohieu/ASUS-K55VD-HACKINTOSH/files/9174837/EFI.zip)

I used the EFI folder from the releases and updated with kext updater

**Comment by javierangulo94** [comment]
This is my EFI

**Comment by cobaohieu** [comment]
Hi, please do not update the kext on your mac OS that you installed. Just put it into EFI folder and use. Please select the zip release version which is the same with your OS.

**Comment by javierangulo94** [comment]
I did the installation again, however, the audio still doesn't work and neither does the hdmi port, what could I do?

**Comment by cobaohieu** [comment]
Can I see your picture?

**Comment by javierangulo94** [comment]
![IMG_20220725_100325](https://user-images.githubusercontent.com/99549336/180811150-9683604d-d9fd-467c-99ed-daad0d05110f.jpg)
![IMG_20220725_100400](https://user-images.githubusercontent.com/99549336/180811217-cff38286-d4d3-4bd1-99c6-1edcd807bed9.jpg)

**Comment by javierangulo94** [comment]
Fixed HDMI and Graphics with the inject Intel with the clover configuration, but i still don't have  audio

**Comment by javierangulo94** [comment]
Fixed Audio with kext command coder
