### ISSUE TITLE
Big sur installation problem

### ISSUE THREAD

**Issue by Duayen** [cobaohieu/ASUS-K55VD-HACKINTOSH#38]
When I start to install big sur on laptop, Opencore menu comes up. After clicking on install big sur, apple loading bar turns black after a while. What can I do for this problem?I used your EFI, in the USB memory I prepared.

**Comment by dlh996** [comment]
i have the same problem...

**Comment by cobaohieu** [comment]
I guess it's just working when you plug in with a monitor through HDMI cable.

**Comment by dlh996** [comment]
> I guess it's just working when you plug in with a monitor through HDMI cable.
Thanks
It works for me.  and now i have other problem to fix. Only hdmi can display

**Comment by Duayen** [comment]
> > I guess it's just working when you plug in with a monitor through HDMI cable.
> > Thanks
> > It works for me.  and now i have other problem to fix. Only hdmi can display

Same problem too for me.

**Comment by Duayen** [comment]
I fixed this issue.Everything on my computer is working now.
