### ISSUE TITLE
Cannot Install Mac OS High Sierra

### ISSUE THREAD

**Issue by quynv186** [cobaohieu/ASUS-K55VD-HACKINTOSH#4]
create usb boot using command 
https://github.com/southernvevo/ASUS-K55VD-HACKINTOSH/blob/master/Command%20Prompt/Guide%20Setup%20macOS%20High%20Sierra%2010.13.txt

When booting, the screen hangs and cannot be install.
you can make more detailed video tutorial?

**Comment by quynv186** [comment]
Bạn có thể giúp tôi cài mac os high sierra trên asus k55vd. tôi đã thử làm theo cách bạn hướng dẫn nhưng k vào màn hình install được.

**Comment by quangtruong16994** [comment]
inbox: quangtruong16994@gmail.com

**Comment by cobaohieu** [comment]
Haiz..

**Comment by quynv186** [comment]
I setup successfully high sierra 10.13.3 with EFI_10.13.2 folder

**Comment by cobaohieu** [comment]
Cẩn thận kẻo mất cái data trên mac nếu dùng APFS, nên dùng HFS+ để mọi thứ ổn.
